articles/urls.py
# 이 파일은 원래 존재하지는 않았고, 내가 따로 new file로 추가해준  `urls.py` 파일임. 
# settings.py에서 include('articles.urls') 라는 함수로 이 urls.py의 경로가 반복되서 사용될 수 있도록 만들어줌. 

from django.urls import path
# 이제 path 앞에는 articles를 빼고 적어도된다. 
from . import views
# 현재 폴더에 있는 views를 가져와요. 

app_name = 'articles'
# 지금 app이 하나 여서 파악이 쉽지만
# 만일, app이 여러개 생기고, 그 안에도 detail이라는 이름을 가진 경로가 있다면
# 헷갈릴 수 있기 때문에
# app_name 설정까지 추가해줌.

# => base.html에 nav가 동작하게끔 넣어줌. 
#  <a class="navbar-brand" href="{% url 'articles: index' %}">  이 부분

urlpatterns = [
    # index = 'articles/' python 스럽게 표현해보자면 
# Read

    path('', views.index, name='index'),
    # name뒤에는 경로에 대한 이름을 지정해줌
    # 유지보수를 편하게 하기 위해서
    path('<int:id>/', views.detail, name='detail'),
    # ''비어 있는 string=> articles경로를 포함하고 있구나.
    # views.py 파일에 이제 함수를 넣어줄 것임. 

# Create
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'), 


# Delete
    path('<int:id>/delete/', views.delete, name='delete'),

# Update
    path('<int:id>/edit/', views.edit, name='edit'),
    path('<int:id>/update/', views.update, name='update' ),

]

board/urls.py
from django.contrib import admin
from django.urls import path, include
# include 함수를 불러와주세요 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls'))


]

articles/models.py
from django.db import models

# base html을 만들어준 뒤, model 설정해주자
# Article

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    # 자동으로 게시물이 작성된 그 순간의 시간을 저장

articles/views.py
from django.shortcuts import render, redirect
from .models import Article

# Create your views here.
def index(request):
    articles = Article.objects.all()
# Read 기능 구현하기

    context = {
        'articles' : articles,
    }
    return render(request, 'index.html', context)
    # 이후 templates 폴더를 'articles'폴더 안에 만들고 index.html 파일을 만들어줌. 

def detail(request, id): 
    article = Article.objects.get(id=id)

    context = {
        'article' : article,
    }

    return render(request, 'detail.html', context)

def new(request):
    return render(request, 'new.html')

def create(request):
    title = request.POST.get('title')
    content = request.POST.get('content')


    article = Article()
    article.title = title
    article.content = content
    article.save()

    return redirect('articles:detail', id=article.id)


def delete(request, id):

    article = Article.objects.get(id=id)
    article.delete()

    return redirect('articles:index')


def edit(request, id):
    article = Article.objects.get(id=id)

    context = {
        'article' : article,
    }
     
    return render(request, 'edit.html', context )

def update(request, id):
    # 기존 정보 가져오기
    article = Article.objects.get(id=id)

    # 새로운 정보 가져오기
    title = request.POST.get('title')
    content = request.POST.get('content')

    # 새로운 정보로 기존 정보를 덮어씌움.
    article.title = title
    article.content = content
    article.save()

    return redirect('articles:detail', id=article.id)

articles/templates/detail.html
{% extends 'base.html' %}

{% block body %}
        <div class="card">
            <div class="card-header">
                {{article.title}}
            </div>
            <div class="card-body">
                {{article.content}}
            </div>
            <div class="card-footer">
                {{article.created_at}}
            </div>

        </div>
<a href="{% url 'articles:delete' article.id %}" class="btn btn-danger mt-2">delete</a>
<a href="{% url 'articles:edit' article.id %}" class="btn btn-warning mt-2">update</a>


{% endblock %}

articles/templates/edit.html
{% extends 'base.html' %}

{% block body %}
    <form action="{% url 'articles:update' article.id %}" method="POST">
         {% csrf_token %}
         
        <div class="mb-3">
            <label for="title" class="form-label">✉️Title</label>
            <input type="text" class="form-control" id="title" name="title" value="{{article.title}}">
        </div>
        <div class="mb-3">
            <label for="content" class="form-label">📝내용 적어용</label>
            <textarea name="content" id="content" class="form-control" rows="10">{{article.content}}</textarea>
        </div>

            <button type="submit" class="btn btn-primary">제출❕ </button>
            <!-- <input type="submit" class="btn btn-primary"> value="제출"> 위 코드와 동일 -->

    </form>
{% endblock %}

articles/templates/index.html
<!-- html 기본 구조의 반복을 줄이기 위해 새로운 templates 라는 이름의 폴더를 외부에 생성하고, 그 안에 `base.html` 파일을 만들어줌. 
 settings.py에 templates 설정을 넣어줌
 settings.py => `TEMPLATES`의    `DIRS` 를 
BASE_DIR / 'templates' -->
 
  {% extends 'base.html' %}

  {% block body %}
   
    <table class="table">
      <thead>
        <tr>
            <th>제목</th>
            <th>내용</th>
            <th>링크</th>
        </tr>
      </thead>
      <tbody>
        {% for article in articles%}
        <!-- article의 수만큼 반복 (articles는 views.py의 변수 articles ) -->
        <tr>
            <td>{{article.title}}</td>
             <td>{{article.content}}</td>
             <td><a href="{% url 'articles:detail' article.id %}" class="btn btn-primary">🫶detail</a></td>
            </tr>
        {% endfor %}
      </tbody>  
    </table>
  {% endblock %}

articles/templates/new.html
{% extends 'base.html' %}

{% block body %}
    <form action="{% url 'articles:create' %}" method="POST">
         {% csrf_token %}
         
        <div class="mb-3">
            <label for="title" class="form-label">✉️Title</label>
            <input type="text" class="form-control" id="title" name="title">
        </div>
        <div class="mb-3">
            <label for="content" class="form-label">📝내용 적어용</label>
            <textarea name="content" id="content" class="form-control" rows="10"></textarea>
        </div>

            <button type="submit" class="btn btn-primary">제출❕ </button>
            <!-- <input type="submit" class="btn btn-primary"> value="제출"> 위 코드와 동일 -->

    </form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'articles:index' %}"> 전체 게시물 목록이🙂</a>

          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link active" aria-current="page" href="{% url 'articles:new' %}">✏️ Create ✏️</a>
              <a class="nav-link" href="#">Features</a>
              <a class="nav-link" href="#">Pricing</a>
            </div>
          </div>
        </div>
      </nav>

    <div class="container">

        {%  block body %}
        <!-- body는 변수이름으로 아무 이름이 들어가도됨 -->
        {% endblock %}

    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>